### ISSUE TITLE
KWoC Backend Revamped

### ISSUE THREAD

**Issue by harshkhandeparkar** [kossiitkgp/KWoC-Backend#101]
The `main` branch of `KWoC-Backend-Revamped` repo has been moved to branch `v2-dev` of this repo to continue futher development under the same repository.

### Work Left
- [x] #104
- [x] #107
- [x] #102
- [x] #109
- Feature parity with backend v1 (remaining routes)
  - [x] #127
  - [x] #128
  - [x] #126
  - [x] #110
  - [x] #116
  - [x] #111
- [x] #120
- [x] #146 
- [x] #129 
- [x] #158

**Comment by rajivharlalka** [comment]
Also add tests, would be easier to have parts tested.

**Comment by harshkhandeparkar** [comment]
> Also add tests, would be easier to have parts tested.

Added to the checklist.

**Comment by Devansh-bit** [comment]
:)

**Comment by harshkhandeparkar** [comment]
damn nice

**Comment by harshkhandeparkar** [comment]
Thanks for your contributions @Devansh-bit! :rocket:
