### ISSUE TITLE
[v2] Healthcheck Routes

### ISSUE THREAD

**Issue by harshkhandeparkar** [kossiitkgp/KWoC-Backend#111]
The following routes should be added for checking the status of the server:
- `/healthcheck/` (GET): Returns the server and database status.
- `/healthcheck/ping/` (GET): A endpoint that responds with the latency. (Used for checking if the server is active)

Suggest any other healtcheck/monitoring routes below.

**Comment by MateSousa** [comment]
@harshkhandeparkar can i try?

**Comment by harshkhandeparkar** [comment]
> @harshkhandeparkar can i try?

Sure! You can start by setting up a local development environment. Ask here if you face any issues :)

**Comment by MateSousa** [comment]
@harshkhandeparkar can you review?
