### ISSUE TITLE
[v2] Documentation

### ISSUE THREAD

**Issue by harshkhandeparkar** [kossiitkgp/KWoC-Backend#120]
The README is missing the following documentation:
- [ ] How to set up a local dev environment
- [ ] Project structure documentation is incomplete/WIP
- [ ] Endpoint documentation
- [ ] How to write tests, test utils, how to run tests

**Comment by proffapt** [comment]
wth, I ain't doing that ( ╯°□°)╯ ┻━━┻

**Comment by harshkhandeparkar** [comment]
oh but you are.
