### ISSUE TITLE
[v2] `/mentor/all/` Route

### ISSUE THREAD

**Issue by harshkhandeparkar** [kossiitkgp/KWoC-Backend#128]
1. [ ] Add a `/mentor/all/` (GET, with login) route to fetch a list of all mentors' basic information.
2. [ ] Add tests for this route.

**Comment by YoganshSharma** [comment]
- In v1, it does not return the mentor who is logged in. Do we have to do that here as well? https://github.com/kossiitkgp/KWoC-Backend/blob/a0ed5910e8013d7c266031c747de027598de9b46/controllers/mentor.go#L101

**Comment by harshkhandeparkar** [comment]
> * In v1, it does not return the mentor who makes the request. Do we have to do that here as well? https://github.com/kossiitkgp/KWoC-Backend/blob/a0ed5910e8013d7c266031c747de027598de9b46/controllers/mentor.go#L101

I guess we can return it. The frontend should handle the exclusion imo.
