### ISSUE TITLE
[v2] Standard JSON Response Format

### ISSUE THREAD

**Issue by harshkhandeparkar** [kossiitkgp/KWoC-Backend#129]
Currently, the format of the responses returned by endpoints is not standard. In some cases, a plain text response is returned, whereas in some cases, it is JSON. Also, the text in the response is different. (For example, there is no standard format for error responses)

A standard JSON format would be better for responses of every endpoint. Please share any ideas below.

**Comment by harshkhandeparkar** [comment]
@Alph3ga @YoganshSharma do you have any suggestions for this?

**Comment by YoganshSharma** [comment]
How about adding a response struct similar to this
```go
type HTTPError struct {
	Code    int    `json:"code" example:"400"`
	Message string `json:"message" example:"status bad request"`
}
```
And refactoring `utils.LogWarnAndRespond` and `utils.LogErrAndRespond` to use this instead.
Some places where these util functions should be used, but they aren't. That also needs to be fixed.

**Comment by harshkhandeparkar** [comment]
> How about adding a response struct similar to this
> 
> ```go
> type HTTPError struct {
> 	Code    int    `json:"code" example:"400"`
> 	Message string `json:"message" example:"status bad request"`
> }
> ```

Works.

> And refactoring `utils.LogWarnAndRespond` and `utils.LogErrAndRespond` to use this instead. Some places where these util functions should be used, but they aren't. That also needs to be fixed.

Which places? (apart from #130 ?)

**Comment by YoganshSharma** [comment]
- In project_reg.go: https://github.com/kossiitkgp/KWoC-Backend/blob/00662b266ce2b7cd487a1880efd9fb0dc7c206ee/controllers/project_reg.go#L58-L59
- In project_update.go: https://github.com/kossiitkgp/KWoC-Backend/blob/00662b266ce2b7cd487a1880efd9fb0dc7c206ee/controllers/project_update.go#L60-L61

**Comment by YoganshSharma** [comment]
ig we should generalize `HTTPError` to a more general name like `HTTPMessage` and use it wherever we are return status code 200 and a message 
like https://github.com/kossiitkgp/KWoC-Backend/blob/00662b266ce2b7cd487a1880efd9fb0dc7c206ee/controllers/mentor.go#L87-L88

**Comment by harshkhandeparkar** [comment]
> * In project_reg.go: https://github.com/kossiitkgp/KWoC-Backend/blob/00662b266ce2b7cd487a1880efd9fb0dc7c206ee/controllers/project_reg.go#L58-L59
> 
>     * In project_update.go: https://github.com/kossiitkgp/KWoC-Backend/blob/00662b266ce2b7cd487a1880efd9fb0dc7c206ee/controllers/project_update.go#L60-L61

Interesting

**Comment by harshkhandeparkar** [comment]
do you want to work on this? self assign if yes. also ig doing this before #150 would be better
