### ISSUE TITLE
[v2] Update Github Actions

### ISSUE THREAD

**Issue by rajivharlalka** [kossiitkgp/KWoC-Backend#137]
- Run tests once a pr is merged. just to be sure nothing breaks after merging.

**Comment by proffapt** [comment]
Then shouldn't it run before merging, when the pr is made?

**Comment by harshkhandeparkar** [comment]
> 

It is run when a PR is made. We just have to run it on `push` as well.

**Comment by proffapt** [comment]
resolved in #141
