### ISSUE TITLE
[v2] API/Endpoint Documentation

### ISSUE THREAD

**Issue by harshkhandeparkar** [kossiitkgp/KWoC-Backend#146]
https://github.com/kossiitkgp/KWoC-Backend/blob/124b8783cacf1811d69b67f3aaf3da34874fa5da/README.md?plain=1#L93-L94

- [x] #149 
- [x] #150

**Comment by harshkhandeparkar** [comment]
@YoganshSharma do you have any suggestions for this?

**Comment by Devansh-bit** [comment]
This should be completed as well
