### ISSUE TITLE
Add Project Status Remark Field

### ISSUE THREAD

**Issue by harshkhandeparkar** [kossiitkgp/KWoC-Backend#168]
Add a new string field `status_remark` to the `Project` db model. This field would contain a message that suggests changes to get a project approved or states the reason for rejection.

**Comment by proffapt** [comment]
Umm, should we do it in the same field as that of project_status.. just increasing the scope of our integers and properly defining what is what?

**Comment by harshkhandeparkar** [comment]
> Umm, should we do it in the same field as that of project_status.. just increasing the scope of our integers and properly defining what is what?

It would be better to have separate fields.
