### ISSUE TITLE
Use Postgres in Development

### ISSUE THREAD

**Issue by harshkhandeparkar** [kossiitkgp/KWoC-Backend#180]
Replace the sqlite3 development database with Postgres to better represent the production environment.

**Comment by shikharish** [comment]
Pls assign me this.

**Comment by shikharish** [comment]
I belive these env variables would also have to be included if postgres is used. And README has to be updated as well.
```
DATABASE_HOST=
DATABASE_PORT=
DATABASE_NAME=
DATABASE_USERNAME=
DATABASE_PORT=
```

**Comment by shikharish** [comment]
@harshkhandeparkar Turns out it won't be as trivial as I thought it would be. The solution I can see right now is using a postgres docker container.

**Comment by harshkhandeparkar** [comment]
> @harshkhandeparkar Turns out it won't be as trivial as I thought it would be. The solution I can see right now is using a postgres docker container.

Hmm. Is there no way to run a postgres db from a file?

**Comment by shikharish** [comment]
We can but I _think_ it would be more difficult to configure(like username, password, port etc. which would be easier in case of a container).

**Comment by shikharish** [comment]
> We can but I _think_ it would be more difficult to configure(like username, password, port etc. which would be easier in case of a container).

We can **import** an SQL file into a postgres database, not run the file.

**Comment by harshkhandeparkar** [comment]
> We can but I _think_ it would be more difficult to configure(like username, password, port etc. which would be easier in case of a container).

So the best way is to set up the container separately?

**Comment by shikharish** [comment]
Yes.

**Comment by harshkhandeparkar** [comment]
How would we do this for the CI tests?
