### ISSUE TITLE
Documentation Builds Are Failing

### ISSUE THREAD

**Issue by harshkhandeparkar** [kossiitkgp/KWoC-Backend#185]
The workflow that builds the API documentation is failing. See [this](https://github.com/kossiitkgp/KWoC-Backend/actions/runs/7248956862/job/19745929770).

**Comment by shikharish** [comment]
@harshkhandeparkar Can you pls assign me this?

**Comment by shikharish** [comment]
How can I test swagger docs locally?

**Comment by harshkhandeparkar** [comment]
> How can I test swagger docs locally?

You will have to run the commands in the [workflow](https://github.com/kossiitkgp/KWoC-Backend/blob/main/.github/workflows/swagger_docs.yml) locally.

@YoganshSharma can you help here?

**Comment by shikharish** [comment]
@harshkhandeparkar Opened a PR. It _should_ fix the bug but havent tested yet.

**Comment by harshkhandeparkar** [comment]
@shikharish It is still not working. See https://github.com/kossiitkgp/KWoC-Backend/actions/runs/7309281337/job/19916739641.

**Comment by shikharish** [comment]
@harshkhandeparkar Hmm. The error is different this time though🤔. Lemme see.

**Comment by shikharish** [comment]
@harshkhandeparkar Can it be run one more time? Weird it just exits without any error.

**Comment by harshkhandeparkar** [comment]
> @harshkhandeparkar Can it be run one more time? Weird it just exits without any error.

https://github.com/kossiitkgp/KWoC-Backend/actions/runs/7313815347

**Comment by harshkhandeparkar** [comment]
There's [this](https://github.com/kossiitkgp/KWoC-Backend/actions/runs/7313815347/job/19925803511#step:8:10) error.

**Comment by shikharish** [comment]
> There's [this](https://github.com/kossiitkgp/KWoC-Backend/actions/runs/7313815347/job/19925803511#step:8:10) error.

Thats not the issue here I think. That warning has been there before the workflow started failing.
Difficult to debug this one honestly. I have set up swaggo locally but not able to reproduce this error. Getting a different error altogether :/

**Comment by harshkhandeparkar** [comment]
@YoganshSharma can you please take a look at this?

**Comment by harshkhandeparkar** [comment]
:smiling_face_with_tear:
