### ISSUE TITLE
Changes in the middleware so that authentication is done in the middleware itself.

### ISSUE THREAD

**Issue by rakaar** [kossiitkgp/KWoC-Backend#40]
The loginRequired middleware works well. But we have to add a check for username in the endpoint everytime like this - https://github.com/kossiitkgp/kwoc20-backend/blob/master/controllers/project.go#L21. Can we make changes in the middleware so that the authentication checks are done in middleware itself.

We can use this modified middleware extensively for authenticated endpoints. Accordingly, in the frontend, we can avoid checking using localStorage and authenticate using this middleware.

Related issue on Frontend - https://github.com/kossiitkgp/KWoC-21-Frontend/issues/9

**Comment by rajivharlalka** [comment]
this has been done
