### ISSUE TITLE
Script to fetch stats and save in DB

### ISSUE THREAD

**Issue by rakaar** [kossiitkgp/KWoC-Backend#44]
Refer - https://github.com/kossiitkgp/kwoc20-backend/wiki/Stats-Plan-for-2021

TODOs
- [ ] Adding in DB (Marked TODO in code)
- [ ] Minor tasks like incrementing/updating a field (Marked TODO in code)
- [ ] Make sure that nobody from outside runs the `/project/stats` endpoint. The function should be called only when a request parameter matches a secret code.

We welcome Pull Requests for individual TODOs :cat:

**Comment by harshkhandeparkar** [comment]
Done in stats API v2.
