### ISSUE TITLE
We are using Supabase!

### ISSUE THREAD

**Issue by rakaar** [kossiitkgp/KWoC-Backend#50]
https://supabase.io/

**Comment by sahil-shubham** [comment]
So no more #48?

**Comment by rakaar** [comment]
@sahil-shubham 
smart! nice catch closed the issue!

**Comment by sahil-shubham** [comment]
I am taking this up, making a supabase account using KOSS GitHub account. 

Also, some steps on how to setup the DB and evironment variables would be good in the README. Looking at how this is an open source  repository and not limited to just KOSS members.

**Comment by rakaar** [comment]
> Also, some steps on how to setup the DB and evironment variables would be good in the README

So how should be our development and Production modes? This is what I propose.

In development mode, just a connection of SQLite DB would suffice right? If that is ok, we can add instructions on setting up a SQLite in development mode. The connection string will be an environment variable. And regarding data. We can provide aa small JSON and a script that dumps some dummy data, which can be useful for testing.

What do u say?

**Comment by sahil-shubham** [comment]
> What do u say?

That sounds good to me. Can you take that up?

**Comment by rakaar** [comment]
@sahil-shubham 
I can take it. But I will start it after Sept 25. Hope its ok, since we have a lot of time.

**Comment by sahil-shubham** [comment]
No hurry. Thanks.
