### ISSUE TITLE
better logging

### ISSUE THREAD

**Issue by sahil-shubham** [kossiitkgp/KWoC-Backend#58]
Need of better log message for easy debugging

**Comment by sheharyaar** [comment]
We can use https://github.com/rs/zerolog for logging, it's optimised and has better logging functionalities. Sample usage : https://github.com/kossiitkgp/KWoC-Backend-Revamped/blob/main/cmd/backend.go#L16-L18

**Comment by sheharyaar** [comment]
Logger middleware sample usage : https://github.com/kossiitkgp/KWoC-Backend-Revamped/blob/main/utils/logger.go
