### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by rajivharlalka** [kossiitkgp/KWoC-Backend#77]
Documentation of the API's can be done. It lacks a lot of information on how to setup the project locally for new comers too.

**Comment by proffapt** [comment]
Isn't docker enough?

**Comment by rajivharlalka** [comment]
but for testing, docker seems a bit pain. a `go run main.go` with a local db seems like a easy solution. nevertheless , we should atleast have a backward compatibility for people not using docker.
