### ISSUE TITLE
Response structure

### ISSUE THREAD

**Issue by rajivharlalka** [kossiitkgp/KWoC-Backend#89]
`/stats/student/<username>` - returns an object in the format
```json
{
    "commit_count": 0,
    "languages": [
        ""
    ],
    "lines_added": 0,
    "lines_removed": 0,
    "name": "Rajiv Harlalka",
    "projects_worked": [
        {
            "name": "",
            "repo_link": ""
        }
    ],
    "pulls": [
        {
            "url": ""
        }
    ],
    "username": "rajivharlalka"
}
```

It would be better to have the pulls array to juts have an array of strings, rather than them being in an array of object with just one key value like this
```json
{
    "commit_count": 0,
    "languages": [
        ""
    ],
    "lines_added": 0,
    "lines_removed": 0,
    "name": "Rajiv Harlalka",
    "projects_worked": [
        {
            "name": "",
            "repo_link": ""
        }
    ],
    "pulls": [
            "url1","url2"
      ],
    "username": "rajivharlalka"
}

Wont be merging the PR related to this issue in master branch this year, as it would break frontend as well. just a refactoring thats good and doable for next year.
```

**Comment by harshkhandeparkar** [comment]
I kept it this way since the frontend used this format already. This also helps us in case we want to track more data for each PR, such as the number of commits. We can change it, but I don't think it's necessary.

**Comment by rajivharlalka** [comment]
Can chnage API reponse this year as the changes would be done on frontend this year, and having a good response structure helps the frontend too to parse the data meaningfully.

**Comment by harshkhandeparkar** [comment]
> Can chnage API reponse this year as the changes would be done on frontend this year, and having a good response structure helps the frontend too to parse the data meaningfully.

Okay, on it.

**Comment by harshkhandeparkar** [comment]
Opened a PR and a frontend issue.
https://github.com/kossiitkgp/KWoC-21-Frontend/issues/116
